demoblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mypost/",include('mypost.urls'))
]

mypost/urls.py
from django.urls import path, include
from mypost import views

app_name = 'mypost'
urlpatterns = [
    # /post/
    path('', views.IndexView.as_view(), name='index'),

    # /post/id/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /post/all/
    path('all/',views.PostListView.as_view(), name='all'),

    # /post/id/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),

    # /post/id/update
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),

    # /post/id/post
    path('post/', views.PostCreateView.as_view(), name='post_create')

]

mypost/models.py
from django.db import models
from datetime import datetime

class Post(models.Model):
    title = models.CharField(max_length=100,null=False)
    author = models.CharField(max_length=20,null=False)
    content = models.TextField(null=False)
    pub_date = models.DateTimeField('date published', default=datetime.now)

    def __str__(self):
        return self.title

mypost/forms.py
from django.forms import ModelForm
from mypost.models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'author', 'content']

mypost/views.py
from django.shortcuts import render
from django.views import generic
from mypost.models import Post
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from mypost.forms import PostForm

class IndexView(generic.ListView):
    template_name = 'mypost/index.html'
    context_object_name = 'latest_post_list'
    def get_queryset(self):
        return Post.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Post
    template_name = 'mypost/detail.html'

class PostListView(generic.ListView):
    template_name = 'mypost/all.html'
    context_object_name = 'all_post_list'

    def get_queryset(self):
        return Post.objects.order_by('-pub_date')

class PostCreateView(CreateView):
    # model = Post
    form_class = PostForm
    context_object_name = 'post_create'
    template_name = 'mypost/create.html'
    success_url = reverse_lazy('mypost:index')

class PostDeleteView(DeleteView):
    model = Post
    context_object_name = 'post_delete'
    template_name='mypost/delete.html'
    success_url = reverse_lazy('mypost:index')
    

class PostUpdateView(UpdateView):
    model = Post
    form_class = PostForm
    context_object_name = 'post_update'
    template_name = 'mypost/update.html'
    success_url = reverse_lazy('mypost:index')
    def get_queryset(self):
        return super().get_queryset().filter()
    

mypost/templates/mypost/all.html
{%extends 'base_post.html'%}
{%block content%}
    <h2>게시글 목록 보기</h2>
    <ul>
        {% for post in all_post_list%}
            <li>
                <h3><a href="/mypost/{{post.pk}}">{{post.title}}</a></h3>
                <p>{{post.author}}</p>
            </li>
        {% endfor %}
    </ul>
{%endblock%}

mypost/templates/mypost/create.html
{% extends 'base_post.html'%}
{% block content %}
    <h2>게시글 작성</h2>
    <form action="{% url 'mypost:post_create'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save</button>
        <a href="/"><button>Quit</button></a>
    </form>
{% endblock %}

mypost/templates/mypost/delete.html
{% extends 'base_post.html' %}

{% block content %}
  <h1>{{ object.title }}"</h1>
  <p>진짜로 지울래?</p>
  <form method="post" url="/mypost/{{object.pk}}/delete/">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="/mypost/">Cancel</a>
  </form>
{% endblock %}

mypost/templates/mypost/detail.html
{% extends 'base_post.html' %}
{%block content%}
    <h1>{{object.title}}</h1>
    <p>{{object.author}}</p>
    <p style="color:gray">{{object.pub_date}}</p>
    {{object.content}}
    <a href="/mypost/{{object.id}}/update/"><button>수정하기</button></a>
    <a href="/mypost/{{object.id}}/delete/"><button>삭제하기</button></a>
{% endblock %}

mypost/templates/mypost/index.html
{% extends 'base_post.html' %}
{%block content%}
<h2>Latest Posts</h2>
<ul>
{%for post in latest_post_list%}
    <li>
        <h3><a href="/mypost/{{post.id}}/">{{post.title}}</a></h3>
        <p><b>{{post.author}}</b></p>
    </li>
{%endfor%}
</ul>
<a href="{%url 'mypost:post_create'%}"><button>글 등록</button></a>
<a href="{%url 'mypost:all' %}"><button>전체 보기</button></a>
{% endblock content %}

mypost/templates/mypost/update.html
{% extends 'base_post.html' %}

{% block content %}
  <h1>Edit</h1>
  <form method="post" url="/mypost/{{object.id}}/update/">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    <a href="/"><button>Quit</button></a>
  </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="{%static 'admin/css/base.css'%}" />
    <title>{%block title%}My Amazing Site{%endblock%}</title>
  </head>
  <body>
    <div id="sidebar">
      {%block sidebar%}
      <ul>
        <li><a href="/">Project_Home</a></li>
        <li><a href="/admin/">Admin</a></li>
      </ul>
      {%endblock%}
    </div>
    <div id="content">{%block content%}{%endblock%}</div>
  </body>
</html>

templates/base_post.html
{% extends "base.html"%}
<title>{% block title %}My blog{%endblock%}</title>

{%block sidebar%}
{{block.super}}
<ul>
  <li><a href="/mypost/">Post_Home</a></li>
</ul>
{%endblock%}